import type { Product } from "@/types/product";
import type { Category } from "@/types/category";
import type { Deal } from "@/types/deal";

// Helper to generate dates relative to now
function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

// Fashion Products
export const sampleProducts: Product[] = [
  {
    id: "prod-1",
    name: "Silk Evening Gown",
    nameAr: "فستان سهرة حريري",
    description: "Exquisite silk evening gown featuring a flowing silhouette with delicate beadwork. Perfect for galas, red carpet events, and special occasions.",
    descriptionAr: "فستان سهرة حريري رائع يتميز بقصة انسيابية مع تطريز دقيق. مثالي للحفلات والمناسبات الخاصة.",
    price: 299.99,
    salePrice: 449.99,
    brand: "Versace",
    images: ["/products/silk-gown.jpg", "/products/silk-gown-2.jpg"],
    category: "women",
    subcategory: "dresses",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Gold", "Burgundy"],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    stockCount: 25,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    tags: ["evening", "silk", "gown", "luxury"],
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-2",
    name: "Italian Leather Handbag",
    nameAr: "حقيبة يد جلد إيطالي",
    description: "Handcrafted Italian leather handbag with gold-tone hardware. Spacious interior with multiple compartments for effortless elegance.",
    descriptionAr: "حقيبة يد من الجلد الإيطالي المصنوع يدوياً مع تفاصيل ذهبية. داخلية واسعة بجيوب متعددة.",
    price: 189.99,
    brand: "Gucci",
    images: ["/products/leather-bag.jpg", "/products/leather-bag-2.jpg"],
    category: "accessories",
    subcategory: "bags",
    sizes: ["OS"],
    colors: ["Tan", "Black", "Cognac"],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 40,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    tags: ["leather", "handbag", "italian", "luxury"],
    createdAt: daysFromNow(-20),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "prod-3",
    name: "Tailored Wool Blazer",
    nameAr: "بليزر صوف مفصل",
    description: "Impeccably tailored wool blazer with a modern slim fit. Premium Italian wool with satin lining for the discerning gentleman.",
    descriptionAr: "بليزر صوف مُفصّل بدقة مع قصة ضيقة عصرية. صوف إيطالي فاخر مع بطانة ساتان.",
    price: 249.99,
    salePrice: 349.99,
    brand: "Armani",
    images: ["/products/wool-blazer.jpg", "/products/wool-blazer-2.jpg"],
    category: "men",
    subcategory: "suits",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Charcoal", "Black"],
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    stockCount: 30,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    tags: ["blazer", "wool", "tailored", "formal"],
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-4",
    name: "Running Sneakers Pro",
    nameAr: "حذاء رياضي برو",
    description: "Advanced running sneakers with responsive cushioning technology and lightweight mesh upper. Engineered for peak performance.",
    descriptionAr: "حذاء رياضي متقدم بتقنية وسائد استجابة وعلوية شبكية خفيفة. مصمم لأقصى أداء.",
    price: 129.99,
    salePrice: 179.99,
    brand: "Nike",
    images: ["/products/running-sneakers.jpg", "/products/running-sneakers-2.jpg"],
    category: "shoes",
    subcategory: "sneakers",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White/Black", "Grey/Volt", "Black/Gold"],
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    stockCount: 80,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    tags: ["running", "sneakers", "athletic", "performance"],
    createdAt: daysFromNow(-15),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-5",
    name: "Organic Face Serum",
    nameAr: "سيروم وجه عضوي",
    description: "Luxurious organic face serum with hyaluronic acid and vitamin C. Visibly reduces fine lines and brightens complexion.",
    descriptionAr: "سيروم وجه عضوي فاخر بحمض الهيالورونيك وفيتامين سي. يقلل الخطوط الدقيقة ويفتح البشرة.",
    price: 59.99,
    brand: "L'Oreal",
    images: ["/products/face-serum.jpg", "/products/face-serum-2.jpg"],
    category: "beauty",
    subcategory: "skincare",
    sizes: ["30ml", "50ml"],
    colors: [],
    rating: 4.5,
    reviewCount: 278,
    inStock: true,
    stockCount: 120,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["organic", "serum", "skincare", "anti-aging"],
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-3),
  },
  {
    id: "prod-6",
    name: "Kids Party Dress",
    nameAr: "فستان حفلة للأطفال",
    description: "Adorable kids party dress with tulle skirt and sequin bodice. Perfect for birthdays, holidays, and special celebrations.",
    descriptionAr: "فستان حفلة للأطفال مع تنترة تول وجسم مرصع. مثالي لأعياد الميلاد والاحتفالات.",
    price: 79.99,
    salePrice: 99.99,
    brand: "Zara",
    images: ["/products/kids-dress.jpg", "/products/kids-dress-2.jpg"],
    category: "kids",
    subcategory: "girls",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink", "White", "Lavender"],
    rating: 4.4,
    reviewCount: 145,
    inStock: true,
    stockCount: 50,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    tags: ["kids", "party", "dress", "girls"],
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-7",
    name: "Designer Sunglasses",
    nameAr: "نظارات شمسية ديزاينر",
    description: "Iconic designer sunglasses with UV400 protection and premium acetate frames. Timeless style meets modern sophistication.",
    descriptionAr: "نظارات شمسية أيقونية بحماية UV400 وإطارات أستيت فاخرة. أسلوب خالد يلتقي بالأناقة العصرية.",
    price: 159.99,
    brand: "Prada",
    images: ["/products/sunglasses.jpg", "/products/sunglasses-2.jpg"],
    category: "accessories",
    subcategory: "sunglasses",
    sizes: ["OS"],
    colors: ["Black", "Tortoise", "Rose Gold"],
    rating: 4.8,
    reviewCount: 201,
    inStock: true,
    stockCount: 35,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    tags: ["sunglasses", "designer", "uv400", "luxury"],
    createdAt: daysFromNow(-18),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "prod-8",
    name: "Cashmere Sweater",
    nameAr: "سترة كشمير",
    description: "Ultra-soft cashmere sweater with a relaxed fit. Ethically sourced Mongolian cashmere for unmatched comfort and warmth.",
    descriptionAr: "سترة كشمير ناعمة فائقة بقصة مريحة. كشمير منغولي من مصادر أخلاقية لراحة ودفء لا مثيل لهما.",
    price: 199.99,
    salePrice: 279.99,
    brand: "Burberry",
    images: ["/products/cashmere-sweater.jpg", "/products/cashmere-sweater-2.jpg"],
    category: "women",
    subcategory: "tops",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Camel", "Grey", "Black"],
    rating: 4.7,
    reviewCount: 267,
    inStock: true,
    stockCount: 45,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    tags: ["cashmere", "sweater", "luxury", "knitwear"],
    createdAt: daysFromNow(-40),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-9",
    name: "Classic Oxford Shoes",
    nameAr: "حذاء أكسفورد كلاسيكي",
    description: "Handmade classic Oxford shoes crafted from premium calfskin leather. Goodyear welted construction for lasting quality.",
    descriptionAr: "حذاء أكسفورد كلاسيكي مصنوع يدوياً من جلد العجل الفاخر. بناء Goodyear welted لجودة دائمة.",
    price: 169.99,
    brand: "Church's",
    images: ["/products/oxford-shoes.jpg", "/products/oxford-shoes-2.jpg"],
    category: "shoes",
    subcategory: "boots",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Dark Brown", "Oxblood"],
    rating: 4.6,
    reviewCount: 178,
    inStock: true,
    stockCount: 28,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["oxford", "leather", "formal", "handmade"],
    createdAt: daysFromNow(-35),
    updatedAt: daysFromNow(-5),
  },
  {
    id: "prod-10",
    name: "Makeup Palette Pro",
    nameAr: "لوحة مكياج برو",
    description: "Professional makeup palette with 24 highly pigmented shades. Matte, shimmer, and metallic finishes for endless looks.",
    descriptionAr: "لوحة مكياج احترافية مع 24 درجة عالية التصبغ. تشطيبات مطفية ولامعة ومعدنية لإطلالات لا متناهية.",
    price: 49.99,
    salePrice: 69.99,
    brand: "MAC",
    images: ["/products/makeup-palette.jpg", "/products/makeup-palette-2.jpg"],
    category: "beauty",
    subcategory: "makeup",
    sizes: ["Standard"],
    colors: [],
    rating: 4.3,
    reviewCount: 334,
    inStock: true,
    stockCount: 85,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    tags: ["makeup", "palette", "professional", "pigmented"],
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-11",
    name: "Smart Watch Luxe",
    nameAr: "ساعة ذكية لوكس",
    description: "Premium smartwatch with titanium case and sapphire crystal display. Advanced health tracking with luxury design.",
    descriptionAr: "ساعة ذكية فاخرة بهيكل تيتانيوم وشاشة كريستال ياقوت. تتبع صحي متقدم بتصميم فاخر.",
    price: 399.99,
    brand: "Apple",
    images: ["/products/smart-watch.jpg", "/products/smart-watch-2.jpg"],
    category: "accessories",
    subcategory: "watches",
    sizes: ["41mm", "45mm"],
    colors: ["Gold", "Silver", "Space Black"],
    rating: 4.9,
    reviewCount: 523,
    inStock: true,
    stockCount: 55,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    tags: ["smartwatch", "luxury", "titanium", "health"],
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-12",
    name: "Men's Activewear Set",
    nameAr: "طقم ملابس رياضية للرجال",
    description: "Performance activewear set with moisture-wicking fabric and four-way stretch. Perfect for gym training and outdoor workouts.",
    descriptionAr: "طقم ملابس رياضية عالي الأداء مع قماش ماص للرطوح وتمدد رباعي. مثالي للتدريب الرياضي.",
    price: 89.99,
    salePrice: 119.99,
    brand: "Adidas",
    images: ["/products/activewear-set.jpg", "/products/activewear-set-2.jpg"],
    category: "men",
    subcategory: "activewear",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Grey"],
    rating: 4.5,
    reviewCount: 298,
    inStock: true,
    stockCount: 90,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    tags: ["activewear", "gym", "performance", "athletic"],
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
  },
];

// Categories for the Persona brand
export const sampleCategories: Category[] = [
  {
    id: "cat-1",
    name: "Women",
    nameAr: "النساء",
    slug: "women",
    image: "/categories/women.jpg",
    description: "Discover women's fashion from the world's top designers",
    descriptionAr: "اكتشفي أزياء النساء من أفضل المصممين العالميين",
    order: 1,
    isActive: true,
  },
  {
    id: "cat-2",
    name: "Men",
    nameAr: "الرجال",
    slug: "men",
    image: "/categories/men.jpg",
    description: "Sharp, sophisticated menswear for the modern gentleman",
    descriptionAr: "أزياء رجالية أنيقة ومتطورة للرجل العصري",
    order: 2,
    isActive: true,
  },
  {
    id: "cat-3",
    name: "Kids",
    nameAr: "الأطفال",
    slug: "kids",
    image: "/categories/kids.jpg",
    description: "Playful and stylish fashion for the little ones",
    descriptionAr: "أزياء مرحة وأنيقة للصغار",
    order: 3,
    isActive: true,
  },
  {
    id: "cat-4",
    name: "Accessories",
    nameAr: "الإكسسوارات",
    slug: "accessories",
    image: "/categories/accessories.jpg",
    description: "Complete your look with luxury accessories",
    descriptionAr: "أكملي إطلالتك بإكسسوارات فاخرة",
    order: 4,
    isActive: true,
  },
  {
    id: "cat-5",
    name: "Shoes",
    nameAr: "الأحذية",
    slug: "shoes",
    image: "/categories/shoes.jpg",
    description: "Step out in style with designer footwear",
    descriptionAr: "خطوة أنيقة بأحذية من أشهر المصممين",
    order: 5,
    isActive: true,
  },
  {
    id: "cat-6",
    name: "Beauty",
    nameAr: "الجمال",
    slug: "beauty",
    image: "/categories/beauty.jpg",
    description: "Premium beauty and skincare essentials",
    descriptionAr: "مستلزمات الجمال والعناية بالبشرة الفاخرة",
    order: 6,
    isActive: true,
  },
  {
    id: "cat-7",
    name: "Sportswear",
    nameAr: "الملابس الرياضية",
    slug: "sportswear",
    image: "/categories/sportswear.jpg",
    description: "High-performance sportswear for every activity",
    descriptionAr: "ملابس رياضية عالية الأداء لكل نشاط",
    order: 7,
    isActive: true,
  },
  {
    id: "cat-8",
    name: "Luxury",
    nameAr: "الفخامة",
    slug: "luxury",
    image: "/categories/luxury.jpg",
    description: "Exclusive luxury pieces for the discerning taste",
    descriptionAr: "قطع فاخرة حصرية للذوق الرفيع",
    order: 8,
    isActive: true,
  },
];

// Flash Deals
export const sampleDeals: Deal[] = [
  {
    id: "deal-1",
    productId: "prod-1",
    title: "Silk Evening Gown Flash Sale",
    titleAr: "عرض فلاش فستان السهرة الحريري",
    discountPercent: 33,
    startsAt: daysFromNow(-1),
    endsAt: daysFromNow(1),
    isActive: true,
    maxQuantity: 30,
    soldCount: 24,
    createdAt: daysFromNow(-1),
  },
  {
    id: "deal-2",
    productId: "prod-3",
    title: "Tailored Wool Blazer Deal",
    titleAr: "عرض البليزر الصوفي المفصل",
    discountPercent: 29,
    startsAt: daysFromNow(-1),
    endsAt: daysFromNow(2),
    isActive: true,
    maxQuantity: 40,
    soldCount: 18,
    createdAt: daysFromNow(-1),
  },
  {
    id: "deal-3",
    productId: "prod-4",
    title: "Running Sneakers Pro Deal",
    titleAr: "عرض الحذاء الرياضي برو",
    discountPercent: 28,
    startsAt: daysFromNow(-2),
    endsAt: daysFromNow(1),
    isActive: true,
    maxQuantity: 100,
    soldCount: 82,
    createdAt: daysFromNow(-2),
  },
  {
    id: "deal-4",
    productId: "prod-8",
    title: "Cashmere Sweater Special",
    titleAr: "عرض سترة الكشمير الخاصة",
    discountPercent: 29,
    startsAt: daysFromNow(-1),
    endsAt: daysFromNow(3),
    isActive: true,
    maxQuantity: 50,
    soldCount: 22,
    createdAt: daysFromNow(-1),
  },
  {
    id: "deal-5",
    productId: "prod-6",
    title: "Kids Party Dress Sale",
    titleAr: "تخفيض فستان الحفلة للأطفال",
    discountPercent: 20,
    startsAt: daysFromNow(-2),
    endsAt: daysFromNow(2),
    isActive: true,
    maxQuantity: 60,
    soldCount: 50,
    createdAt: daysFromNow(-2),
  },
  {
    id: "deal-6",
    productId: "prod-12",
    title: "Men's Activewear Flash Deal",
    titleAr: "عرض فلاش طقم الرياضة للرجال",
    discountPercent: 25,
    startsAt: daysFromNow(-1),
    endsAt: daysFromNow(2),
    isActive: true,
    maxQuantity: 120,
    soldCount: 95,
    createdAt: daysFromNow(-1),
  },
];

// Brand names for marquee
export const brandNames = [
  "Versace",
  "Gucci",
  "Armani",
  "Nike",
  "Prada",
  "Burberry",
  "Zara",
  "H&M",
  "L'Oreal",
  "Adidas",
  "Dolce & Gabbana",
  "Chanel",
];
