import type { Product } from "@/types/product";
import type { Category } from "@/types/category";
import type { Deal } from "@/types/deal";

// Helper to generate dates 2-3 days from now
function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

// Products
export const sampleProducts: Product[] = [
  {
    id: "prod-1",
    name: "Wireless Headphones",
    nameAr: "سماعات لاسلكية",
    slug: "wireless-headphones",
    description: "Premium wireless headphones with active noise cancellation and 30-hour battery life. Crystal clear sound with deep bass for an immersive listening experience.",
    descriptionAr: "سماعات لاسلكية متميزة مع إلغاء الضوضاء النشط وبطارية تدوم ٣٠ ساعة. صوت نقي مع باس عميق لتجربة استماع غامرة.",
    price: 79.99,
    originalPrice: 129.99,
    discount: 38,
    currency: "USD",
    images: [],
    variants: [
      { id: "v1-1", name: "Color", value: "Black", stock: 45, priceAdjustment: 0 },
      { id: "v1-2", name: "Color", value: "White", stock: 30, priceAdjustment: 0 },
    ],
    categoryId: "cat-1",
    category: "Electronics",
    rating: 4.5,
    reviewCount: 234,
    stock: 75,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    tags: ["wireless", "headphones", "noise-cancelling"],
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-2",
    name: "Silk Summer Dress",
    nameAr: "فستان صيفي حريري",
    slug: "silk-summer-dress",
    description: "Elegant silk summer dress perfect for any occasion. Lightweight and breathable fabric with a flattering A-line silhouette.",
    descriptionAr: "فستان صيفي أنيق من الحرير مثالي لأي مناسبة. قماش خفيف ومريح مع تصميم يبرز القوام.",
    price: 49.99,
    originalPrice: 89.99,
    discount: 44,
    currency: "USD",
    images: [],
    variants: [
      { id: "v2-1", name: "Size", value: "S", stock: 15, priceAdjustment: 0 },
      { id: "v2-2", name: "Size", value: "M", stock: 25, priceAdjustment: 0 },
      { id: "v2-3", name: "Size", value: "L", stock: 20, priceAdjustment: 0 },
    ],
    categoryId: "cat-2",
    category: "Fashion",
    rating: 4.8,
    reviewCount: 189,
    stock: 60,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    tags: ["dress", "silk", "summer", "fashion"],
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-3",
    name: "Smart Watch Pro",
    nameAr: "ساعة ذكية برو",
    slug: "smart-watch-pro",
    description: "Advanced smartwatch with health monitoring, GPS tracking, and a stunning AMOLED display. Water resistant up to 50m.",
    descriptionAr: "ساعة ذكية متطورة مع مراقبة صحية وتتبع GPS وشاشة AMOLED مذهلة. مقاومة للماء حتى ٥٠ متر.",
    price: 199.99,
    originalPrice: 299.99,
    discount: 33,
    currency: "USD",
    images: [],
    variants: [
      { id: "v3-1", name: "Size", value: "42mm", stock: 40, priceAdjustment: 0 },
      { id: "v3-2", name: "Size", value: "46mm", stock: 35, priceAdjustment: 20 },
    ],
    categoryId: "cat-1",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 312,
    stock: 75,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    tags: ["smartwatch", "fitness", "gps"],
    createdAt: daysFromNow(-45),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "prod-4",
    name: "Organic Face Cream",
    nameAr: "كريم وجه عضوي",
    slug: "organic-face-cream",
    description: "Nourishing organic face cream with natural ingredients. Hydrates and rejuvenates skin for a youthful glow.",
    descriptionAr: "كريم وجه عضوي مغذي بمكونات طبيعية. يرطب ويجدد البشرة لإشراقة شابة.",
    price: 34.99,
    originalPrice: undefined,
    discount: undefined,
    currency: "USD",
    images: [],
    variants: [
      { id: "v4-1", name: "Size", value: "50ml", stock: 100, priceAdjustment: 0 },
      { id: "v4-2", name: "Size", value: "100ml", stock: 60, priceAdjustment: 15 },
    ],
    categoryId: "cat-4",
    category: "Beauty",
    rating: 4.3,
    reviewCount: 156,
    stock: 160,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["organic", "skincare", "face-cream"],
    createdAt: daysFromNow(-20),
    updatedAt: daysFromNow(-3),
  },
  {
    id: "prod-5",
    name: "Running Shoes Elite",
    nameAr: "حذاء رياضي للجري",
    slug: "running-shoes-elite",
    description: "High-performance running shoes with responsive cushioning and lightweight design. Perfect for marathon training.",
    descriptionAr: "حذاء رياضي عالي الأداء مع وسائد استجابة وتصميم خفيف. مثالي لتدريب الماراثون.",
    price: 89.99,
    originalPrice: 139.99,
    discount: 36,
    currency: "USD",
    images: [],
    variants: [
      { id: "v5-1", name: "Size", value: "42", stock: 20, priceAdjustment: 0 },
      { id: "v5-2", name: "Size", value: "44", stock: 15, priceAdjustment: 0 },
    ],
    categoryId: "cat-5",
    category: "Sports",
    rating: 4.6,
    reviewCount: 201,
    stock: 35,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    tags: ["running", "shoes", "sports"],
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-6",
    name: "Stainless Steel Blender",
    nameAr: "خلاط من الستانلس ستيل",
    slug: "stainless-steel-blender",
    description: "Powerful stainless steel blender with multiple speed settings. Perfect for smoothies, soups, and more.",
    descriptionAr: "خلاط قوي من الستانلس ستيل مع إعدادات سرعة متعددة. مثالي للعصائر والحساء والمزيد.",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    currency: "USD",
    images: [],
    variants: [],
    categoryId: "cat-3",
    category: "Home",
    rating: 4.4,
    reviewCount: 178,
    stock: 90,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["blender", "kitchen", "home"],
    createdAt: daysFromNow(-15),
    updatedAt: daysFromNow(-5),
  },
  {
    id: "prod-7",
    name: "Yoga Mat Premium",
    nameAr: "سجادة يوغا فاخرة",
    slug: "yoga-mat-premium",
    description: "Non-slip premium yoga mat with alignment marks. Extra thick for comfort during long sessions.",
    descriptionAr: "سجادة يوغا فاخرة غير قابلة للانزلاق مع علامات المحاذاة. سميكة إضافية للراحة أثناء الجلسات الطويلة.",
    price: 29.99,
    originalPrice: undefined,
    discount: undefined,
    currency: "USD",
    images: [],
    variants: [
      { id: "v7-1", name: "Color", value: "Purple", stock: 40, priceAdjustment: 0 },
      { id: "v7-2", name: "Color", value: "Green", stock: 35, priceAdjustment: 0 },
    ],
    categoryId: "cat-5",
    category: "Sports",
    rating: 4.2,
    reviewCount: 134,
    stock: 75,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["yoga", "fitness", "mat"],
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(-7),
  },
  {
    id: "prod-8",
    name: "Bestseller Novel Collection",
    nameAr: "مجموعة روايات الأكثر مبيعاً",
    slug: "bestseller-novel-collection",
    description: "A curated collection of 5 bestselling novels from renowned authors. Perfect for book lovers.",
    descriptionAr: "مجموعة منتقاة من ٥ روايات الأكثر مبيعاً من مؤلفين مشهورين. مثالية لمحبي الكتب.",
    price: 19.99,
    originalPrice: undefined,
    discount: undefined,
    currency: "USD",
    images: [],
    variants: [],
    categoryId: "cat-6",
    category: "Books",
    rating: 4.9,
    reviewCount: 423,
    stock: 200,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    tags: ["books", "novels", "bestseller"],
    createdAt: daysFromNow(-60),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "prod-9",
    name: "Kids Educational Toy Set",
    nameAr: "مجموعة ألعاب تعليمية للأطفال",
    slug: "kids-educational-toy-set",
    description: "Fun and educational toy set with 50+ pieces. Develops creativity, motor skills, and problem-solving abilities.",
    descriptionAr: "مجموعة ألعاب ممتعة وتعليمية مع أكثر من ٥٠ قطعة. تطور الإبداع والمهارات الحركية وقدرات حل المشكلات.",
    price: 44.99,
    originalPrice: 59.99,
    discount: 25,
    currency: "USD",
    images: [],
    variants: [
      { id: "v9-1", name: "Age", value: "3-5", stock: 30, priceAdjustment: 0 },
      { id: "v9-2", name: "Age", value: "6-8", stock: 25, priceAdjustment: 5 },
    ],
    categoryId: "cat-7",
    category: "Toys",
    rating: 4.5,
    reviewCount: 167,
    stock: 55,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    tags: ["toys", "educational", "kids"],
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-10",
    name: "Wireless Charging Pad",
    nameAr: "شاحن لاسلكي",
    slug: "wireless-charging-pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator.",
    descriptionAr: "شاحن لاسلكي سريع متوافق مع جميع أجهزة Qi. تصميم أنيق مع مؤشر LED.",
    price: 24.99,
    originalPrice: 39.99,
    discount: 38,
    currency: "USD",
    images: [],
    variants: [],
    categoryId: "cat-1",
    category: "Electronics",
    rating: 4.1,
    reviewCount: 98,
    stock: 150,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    tags: ["wireless", "charger", "electronics"],
    createdAt: daysFromNow(-18),
    updatedAt: daysFromNow(-4),
  },
  {
    id: "prod-11",
    name: "Leather Crossbody Bag",
    nameAr: "حقيبة جلدية كروس بودي",
    slug: "leather-crossbody-bag",
    description: "Genuine leather crossbody bag with adjustable strap. Multiple compartments for organized storage.",
    descriptionAr: "حقيبة جلدية أصلية بحزام قابل للتعديل. جيوب متعددة لتخزين منظم.",
    price: 69.99,
    originalPrice: 99.99,
    discount: 30,
    currency: "USD",
    images: [],
    variants: [
      { id: "v11-1", name: "Color", value: "Brown", stock: 25, priceAdjustment: 0 },
      { id: "v11-2", name: "Color", value: "Black", stock: 30, priceAdjustment: 0 },
    ],
    categoryId: "cat-2",
    category: "Fashion",
    rating: 4.7,
    reviewCount: 245,
    stock: 55,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    tags: ["bag", "leather", "fashion", "crossbody"],
    createdAt: daysFromNow(-35),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "prod-12",
    name: "Premium Coffee Maker",
    nameAr: "صانعة قهوة فاخرة",
    slug: "premium-coffee-maker",
    description: "Premium coffee maker with built-in grinder and programmable settings. Brews the perfect cup every time.",
    descriptionAr: "صانعة قهوة فاخرة مع مطحنة مدمجة وإعدادات قابلة للبرمجة. تحضر الكوب المثالي في كل مرة.",
    price: 149.99,
    originalPrice: 199.99,
    discount: 25,
    currency: "USD",
    images: [],
    variants: [],
    categoryId: "cat-3",
    category: "Home",
    rating: 4.8,
    reviewCount: 287,
    stock: 40,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    tags: ["coffee", "kitchen", "home", "appliance"],
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
  },
];

// Categories
export const sampleCategories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    nameAr: "إلكترونيات",
    slug: "electronics",
    description: "Latest gadgets and electronic devices",
    descriptionAr: "أحدث الأجهزة والإلكترونيات",
    image: "",
    icon: "💻",
    productCount: 240,
    subcategories: [],
    isFeatured: true,
    displayOrder: 1,
  },
  {
    id: "cat-2",
    name: "Fashion",
    nameAr: "أزياء",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    descriptionAr: "ملابس وإكسسوارات عصرية",
    image: "",
    icon: "👗",
    productCount: 380,
    subcategories: [],
    isFeatured: true,
    displayOrder: 2,
  },
  {
    id: "cat-3",
    name: "Home & Kitchen",
    nameAr: "المنزل والمطبخ",
    slug: "home",
    description: "Everything for your home and kitchen",
    descriptionAr: "كل ما تحتاجه لمنزلك ومطبخك",
    image: "",
    icon: "🏠",
    productCount: 190,
    subcategories: [],
    isFeatured: true,
    displayOrder: 3,
  },
  {
    id: "cat-4",
    name: "Beauty",
    nameAr: "الجمال",
    slug: "beauty",
    description: "Skincare, makeup, and beauty essentials",
    descriptionAr: "العناية بالبشرة والمكياج ولوازم الجمال",
    image: "",
    icon: "✨",
    productCount: 150,
    subcategories: [],
    isFeatured: true,
    displayOrder: 4,
  },
  {
    id: "cat-5",
    name: "Sports",
    nameAr: "رياضة",
    slug: "sports",
    description: "Sports equipment and activewear",
    descriptionAr: "معدات رياضية وملابس رياضية",
    image: "",
    icon: "⚽",
    productCount: 120,
    subcategories: [],
    isFeatured: false,
    displayOrder: 5,
  },
  {
    id: "cat-6",
    name: "Books",
    nameAr: "كتب",
    slug: "books",
    description: "Bestselling books and literature",
    descriptionAr: "الكتب والروايات الأكثر مبيعاً",
    image: "",
    icon: "📚",
    productCount: 310,
    subcategories: [],
    isFeatured: false,
    displayOrder: 6,
  },
  {
    id: "cat-7",
    name: "Toys",
    nameAr: "ألعاب",
    slug: "toys",
    description: "Fun and educational toys for all ages",
    descriptionAr: "ألعاب ممتعة وتعليمية لجميع الأعمار",
    image: "",
    icon: "🧩",
    productCount: 95,
    subcategories: [],
    isFeatured: false,
    displayOrder: 7,
  },
  {
    id: "cat-8",
    name: "Groceries",
    nameAr: "بقالة",
    slug: "groceries",
    description: "Fresh groceries and everyday essentials",
    descriptionAr: "بقالة طازجة ولوازم يومية",
    image: "",
    icon: "🍎",
    productCount: 200,
    subcategories: [],
    isFeatured: false,
    displayOrder: 8,
  },
];

// Deals
export const sampleDeals: Deal[] = [
  {
    id: "deal-1",
    title: "Wireless Headphones",
    titleAr: "سماعات لاسلكية",
    description: "Premium wireless headphones at unbeatable price",
    descriptionAr: "سماعات لاسلكية متميزة بسعر لا يُقاوم",
    image: "",
    discountPercentage: 38,
    originalPrice: 129.99,
    dealPrice: 79.99,
    currency: "USD",
    startDate: daysFromNow(-1),
    endDate: daysFromNow(2),
    totalStock: 100,
    soldStock: 72,
    isActive: true,
    isFeatured: true,
    badge: "Hot Deal",
    badgeAr: "عرض ساخن",
  },
  {
    id: "deal-2",
    title: "Smart Watch Pro",
    titleAr: "ساعة ذكية برو",
    description: "Advanced smartwatch with massive discount",
    descriptionAr: "ساعة ذكية متطورة بخصم كبير",
    image: "",
    discountPercentage: 33,
    originalPrice: 299.99,
    dealPrice: 199.99,
    currency: "USD",
    startDate: daysFromNow(-1),
    endDate: daysFromNow(3),
    totalStock: 80,
    soldStock: 45,
    isActive: true,
    isFeatured: true,
    badge: "Best Value",
    badgeAr: "أفضل قيمة",
  },
  {
    id: "deal-3",
    title: "Silk Summer Dress",
    titleAr: "فستان صيفي حريري",
    description: "Elegant silk dress at 44% off",
    descriptionAr: "فستان حريري أنيق بخصم ٤٤٪",
    image: "",
    discountPercentage: 44,
    originalPrice: 89.99,
    dealPrice: 49.99,
    currency: "USD",
    startDate: daysFromNow(-2),
    endDate: daysFromNow(1),
    totalStock: 60,
    soldStock: 52,
    isActive: true,
    isFeatured: false,
    badge: "Almost Gone",
    badgeAr: "شارف على النفاد",
  },
  {
    id: "deal-4",
    title: "Running Shoes Elite",
    titleAr: "حذاء رياضي للجري",
    description: "High-performance running shoes on sale",
    descriptionAr: "حذاء رياضي عالي الأداء في التخفيضات",
    image: "",
    discountPercentage: 36,
    originalPrice: 139.99,
    dealPrice: 89.99,
    currency: "USD",
    startDate: daysFromNow(-1),
    endDate: daysFromNow(2),
    totalStock: 50,
    soldStock: 30,
    isActive: true,
    isFeatured: false,
    badge: "Flash Deal",
    badgeAr: "عرض سريع",
  },
  {
    id: "deal-5",
    title: "Premium Coffee Maker",
    titleAr: "صانعة قهوة فاخرة",
    description: "Brew perfection with 25% off",
    descriptionAr: "إعداد مثالي بخصم ٢٥٪",
    image: "",
    discountPercentage: 25,
    originalPrice: 199.99,
    dealPrice: 149.99,
    currency: "USD",
    startDate: daysFromNow(-1),
    endDate: daysFromNow(3),
    totalStock: 40,
    soldStock: 18,
    isActive: true,
    isFeatured: true,
    badge: "Limited",
    badgeAr: "محدود",
  },
  {
    id: "deal-6",
    title: "Leather Crossbody Bag",
    titleAr: "حقيبة جلدية كروس بودي",
    description: "Genuine leather bag at 30% off",
    descriptionAr: "حقيبة جلدية أصلية بخصم ٣٠٪",
    image: "",
    discountPercentage: 30,
    originalPrice: 99.99,
    dealPrice: 69.99,
    currency: "USD",
    startDate: daysFromNow(-2),
    endDate: daysFromNow(2),
    totalStock: 55,
    soldStock: 40,
    isActive: true,
    isFeatured: false,
    badge: "Trending",
    badgeAr: "رائج",
  },
];

// Brand names
export const brandNames = [
  "Nike",
  "Adidas",
  "Apple",
  "Samsung",
  "Sony",
  "Zara",
  "H&M",
  "L'Oreal",
  "Puma",
  "Unilever",
  "Dyson",
  "Bose",
];
